name: geohmount
channels:
  - conda-forge
  - plotly
  - defaults
dependencies:
  - python=3.9
  - pandas=1.3
  - matplotlib=3.4
  - seaborn=0.11
  - plotly=5.2
  - python-kaleido=0.2
  - ipykernel=6.2
  - notebook=6.4
  - python-dotenv=0.19
  - chart_studio=1.1